language: php

sudo: false

php:
  - '5.6'
  - '7.0'
  - '7.1'

cache:
  directories:
    - $HOME/.composer/cache/files

install:
  - composer update --no-interaction --no-progress --no-suggest --prefer-dist

script:
  - vendor/bin/phpunit

notifications:
  email: false
